#!/usr/bin/env bash
# init.sh — content-pipeline-stack installer
# 纯源码模式: clone 仓库后, 跑这个脚本, 启 registry + push image + 跑 docker compose up
#
# 设计原则:
#   - 不需要 douyin-data 迁移 (用你自己的数据)
#   - 不需要 init data (registry 装好后, 自己准备 mp4/upload 即可)
#   - 路径全 ENV-driven, 改 .env 即可
#
# 使用:
#   git clone <repo> /opt/content-pipeline-stack
#   cd /opt/content-pipeline-stack
#   bash init.sh
#
# 步骤:
#   1. 问 4 个关键路径 (data / uploads / openclaw / recorder)
#   2. 写 .env (覆盖 .env.example)
#   3. 启本地 registry:2 容器
#   4. rebuild 10 image (不依赖外部 registry)
#   5. push 到 localhost:5000
#   6. docker compose up (默认 4 服务: content-pipeline-mcp + file-service + douyin-recorder + v6-monitor)

set -euo pipefail

# ═══════════════════════════════════════════════════════════════
# Constants
# ═══════════════════════════════════════════════════════════════
STACK_NAME="content-pipeline-stack"
IMAGE_TAG="${IMAGE_TAG:-0.1.0}"
REGISTRY_PORT="${REGISTRY_PORT:-5000}"

# ═══════════════════════════════════════════════════════════════
# Helpers
# ═══════════════════════════════════════════════════════════════
log()   { printf "\033[1;34m[%s]\033[0m %s\n" "$(date +%H:%M:%S)" "$*"; }
warn()  { printf "\033[1;33m[WARN]\033[0m %s\n" "$*"; }
fail()  { printf "\033[1;31m[FAIL]\033[0m %s\n" "$*" >&2; exit 1; }
ok()    { printf "\033[1;32m[OK]\033[0m %s\n" "$*"; }

ask() {
    local prompt="$1"
    local default="$2"
    local var="$3"
    local reply
    read -r -p "$(printf "\033[1;36m%s\033[0m [%s]: " "$prompt" "$default")" reply
    if [ -z "$reply" ]; then
        eval "$var=\"\$default\""
    else
        eval "$var=\"\$reply\""
    fi
}

# ═══════════════════════════════════════════════════════════════
# Pre-checks
# ═══════════════════════════════════════════════════════════════
log "═══════════════════════════════════════════════════════════"
log " $STACK_NAME installer"
log "═══════════════════════════════════════════════════════════"
echo ""

[ "$(id -u)" = "0" ] && fail "不要用 root 跑 (容器内 UID 1001, 需要 host user 同 UID)"

command -v docker >/dev/null || fail "docker 未装"
docker info >/dev/null 2>&1 || fail "docker daemon 未启"
docker compose version >/dev/null 2>&1 || fail "docker compose plugin 未装"
[ ! -f docker-compose.yml ] && fail "在 $STACK_NAME 目录跑 (cd $STACK_NAME && bash init.sh)"

# ═══════════════════════════════════════════════════════════════
# Step 1: 问 4 个关键路径
# ═══════════════════════════════════════════════════════════════
log "Step 1/6: 配置路径"
echo ""
echo "  这 4 个路径是 stack 的数据盘, 必须存在。"
echo "  如果你是 HK 用户, 默认值就 OK。"
echo ""

# 探测当前用户 UID, 提示
USER_UID=$(id -u)
USER_GID=$(id -g)

ask "主数据目录 (queue.db / state.db / transcripts / videos)" "/home/main/douyin-data" "DATA_DIR"
ask "上传目录 (file-service upload 后落这)" "/home/main/uploads" "UPLOADS_DIR"
ask "OpenClaw 工作区 (skills 源码路径)" "/home/main/.openclaw" "OPENCLAW_DIR"
ask "douyin-recorder 源码目录" "/home/main/DouyinLiveRecorder" "RECORDER_DIR"

# Playwright 缓存自动探测
PLAYWRIGHT_DIR=""
for d in "/home/main/.cache/ms-playwright" "/home/$USER/.cache/ms-playwright" "/root/.cache/ms-playwright"; do
    [ -d "$d" ] && PLAYWRIGHT_DIR="$d" && break
done
[ -z "$PLAYWRIGHT_DIR" ] && PLAYWRIGHT_DIR="/home/main/.cache/ms-playwright"
echo ""
log "Playwright cache: $PLAYWRIGHT_DIR (v6-download 用 chromium fallback)"

# Host ASR URL 探测 (HK 默认 18200)
HK_ASR_URL="http://host.docker.internal:18200"
ask "HK ASR URL (transcribe worker 调)" "$HK_ASR_URL" "HK_ASR_URL"

# File-service URL (容器内用 service name)
FILE_SERVICE_URL="http://file-service:18098"

# ═══════════════════════════════════════════════════════════════
# Step 2: 写 .env
# ═══════════════════════════════════════════════════════════════
log ""
log "Step 2/6: 写 .env"
[ -f .env ] && warn ".env 已存在, 覆盖 (按 Enter) / 备份 (输入 b) ?"
read -r -p "  [Y/b]: " reply
if [ "$reply" = "b" ]; then
    cp .env .env.bak-$(date +%Y%m%d-%H%M%S)
    log "已备份 .env"
fi

cat > .env << EOF
# content-pipeline-stack — .env (auto-generated by init.sh @ $(date +%Y-%m-%d\ %H:%M:%S))
# 别人改这里就能切路径 (不用改代码)

# ─── 关键路径 ───
DATA_DIR=$DATA_DIR
UPLOADS_DIR=$UPLOADS_DIR
OPENCLAW_DIR=$OPENCLAW_DIR
RECORDER_DIR=$RECORDER_DIR
PLAYWRIGHT_DIR=$PLAYWRIGHT_DIR

# ─── 镜像仓库 (本地 registry:2 容器) ───
REGISTRY_URL=localhost:$REGISTRY_PORT
IMAGE_TAG=$IMAGE_TAG

# ─── 外部服务 ───
HK_ASR_URL=$HK_ASR_URL
FILE_SERVICE_URL=$FILE_SERVICE_URL

# ─── 时区 ───
TZ=Asia/Shanghai

# ─── 安全 tokens (init.sh 不写, 你自己填, 否则用 empty 默认) ───
MCP_TOKEN=
FS_UPLOAD_TOKEN=
YUXI_TOKEN=
YUXI_BASE_URL=
DOUYIN_RECORDER_DASHBOARD_TOKEN=
EOF
ok ".env 写好"

# ═══════════════════════════════════════════════════════════════
# Step 3: 检查路径存在
# ═══════════════════════════════════════════════════════════════
log ""
log "Step 3/6: 检查路径"
for path in "$DATA_DIR" "$UPLOADS_DIR" "$OPENCLAW_DIR"; do
    [ -d "$path" ] || fail "$path 不存在, mkdir -p $path 后再跑"
    ok "$path"
done
[ -d "$RECORDER_DIR" ] && ok "$RECORDER_DIR" || warn "$RECORDER_DIR 不存在 (douyin-recorder 服务会起不来)"

# ═══════════════════════════════════════════════════════════════
# Step 4: 启 registry:2
# ═══════════════════════════════════════════════════════════════
log ""
log "Step 4/6: 启本地 registry:2 (port $REGISTRY_PORT)"
if docker ps -a --format '{{.Names}}' | grep -q '^registry$'; then
    ok "registry 容器已存在"
    docker start registry 2>/dev/null || true
else
    mkdir -p /home/$USER/docker-registry
    docker run -d \
        --name registry \
        --restart unless-stopped \
        -p $REGISTRY_PORT:5000 \
        -v /home/$USER/docker-registry:/var/lib/registry \
        registry:2
    ok "registry:2 起 (数据卷 /home/$USER/docker-registry/)"
fi

# ═══════════════════════════════════════════════════════════════
# Step 5: rebuild 10 image + push
# ═══════════════════════════════════════════════════════════════
log ""
log "Step 5/6: rebuild + push 10 image"

# 共 6 个 base + 9 个 service image (v6-base 被 5 worker 复用)
images=(
    "content-pipeline-mcp:services/content-pipeline-mcp"
    "file-service:services/file-service"
    "douyin-recorder:services/douyin-recorder/source"
    "v6-base:services/v6-base"
    "v6-enqueue:services/v6-enqueue"
    "v6-download:services/v6-download"
    "v6-transcribe:services/v6-transcribe"
    "v6-distill:services/v6-distill"
    "v6-upload:services/v6-upload"
    "v6-monitor:services/v6-monitor"
)

for entry in "${images[@]}"; do
    name="${entry%%:*}"
    ctx="${entry#*:}"
    if [ "$name" = "douyin-recorder" ]; then
        dockerfile="-f Dockerfile"
        build_ctx="services/douyin-recorder/source"
    elif [[ "$name" == v6-* && "$name" != "v6-base" ]]; then
        # v6 worker 用 v6-base 为 build context (FROM 行)
        dockerfile="-f Dockerfile"
        build_ctx="services/v6-base"
    else
        dockerfile=""
        build_ctx="$ctx"
    fi
    log "  build $name:$IMAGE_TAG"
    docker build $dockerfile -t localhost:$REGISTRY_PORT/$STACK_NAME/$name:$IMAGE_TAG $build_ctx 2>&1 | tail -1
    docker push localhost:$REGISTRY_PORT/$STACK_NAME/$name:$IMAGE_TAG 2>&1 | tail -1
done
ok "10 image 推完"

# ═══════════════════════════════════════════════════════════════
# Step 6: docker compose up
# ═══════════════════════════════════════════════════════════════
log ""
log "Step 6/6: docker compose up (默认 4 服务)"

docker compose up -d 2>&1 | tail -5
echo ""
sleep 15

log ""
log "═══════════════════════════════════════════════════════════"
log " $STACK_NAME 部署完成!"
log "═══════════════════════════════════════════════════════════"
echo ""
echo "  9 服务 (4 default + 5 profile=workers):"
docker ps --format "  - {{.Names}}: {{.Status}}" | grep -E "content-pipeline|file-service|v6-|douyin-recorder" | sort
echo ""
echo "  访问地址 (HK 当前):"
echo "    - content-pipeline-mcp:  http://localhost:28092"
echo "    - file-service:          http://localhost:28098"
echo ""
echo "  启 5 v6-worker (可选):"
echo "    docker compose --profile v6-workers up -d"
echo ""
echo "  systemd 还在跑的服务 (旧 systemd 还没切):"
echo "    - douyin-recorder:        Active=$(systemctl is-active douyin-recorder 2>/dev/null || echo unknown)"
echo "    - v6-monitor / v6-worker:  Active=$(systemctl is-active v6-monitor 2>/dev/null || echo unknown)"
echo ""
echo "  切 systemd → docker (需 sudo):"
echo "    sudo systemctl stop v6-monitor v6-enqueue v6-download v6-transcribe v6-distill v6-upload douyin-recorder"
echo "    sudo systemctl disable v6-monitor v6-enqueue v6-download v6-transcribe v6-distill v6-upload douyin-recorder"
echo "    docker compose --profile v6-workers up -d"
echo ""
log "Done."